import { useState, useEffect } from 'react';
import { getDashboard } from '../../api/electro/reports';
import { Card } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Spinner } from '../../components/ui/Spinner';
import { useAuth } from '../../hooks/useAuth';
import { formatCurrency } from '../../utils/format';
import { Printer, Package, ShoppingCart, Wrench, DollarSign } from 'lucide-react';

export default function Reports() {
  const { user } = useAuth();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const businessName = user?.businessName || 'ElectroStore';

  useEffect(() => { getDashboard().then(res => setData(res?.data || res)).catch(() => {}).finally(() => setLoading(false)); }, []);

  const handlePrint = () => {
    const now = new Date().toLocaleString('en-KE');
    const html = `<!DOCTYPE html><html><head><title>Report</title><style>@page{size:A4;margin:12mm;}body{font-family:Arial;font-size:11px;}.header{text-align:center;border-bottom:2px solid #f59e0b;padding-bottom:10px;margin-bottom:14px;}.header h2{color:#f59e0b;}.summary{background:#fffbeb;padding:12px;border-radius:6px;margin-bottom:12px;}.row{display:flex;justify-content:space-between;padding:4px 0;border-bottom:1px dotted #fde68a;}.total{font-weight:700;border-top:1px solid #f59e0b;padding-top:6px;}.footer{text-align:center;margin-top:16px;font-size:9px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:10px;}</style></head><body><div class="header"><h2>${businessName}</h2><p>Electronics Report</p></div><div class="summary"><div class="row"><span>Products</span><span>${data?.totalProducts||0}</span></div><div class="row"><span>Low Stock</span><span>${data?.lowStock||0}</span></div><div class="row"><span>Today Sales</span><span>${data?.todaySales||0}</span></div><div class="row"><span>Active Repairs</span><span>${data?.activeRepairs||0}</span></div><div class="row total"><span>Monthly Revenue</span><span>${formatCurrency(data?.monthRevenue||0)}</span></div></div><div class="footer">Generated by ElectroStore &mdash; ${now}</div></body></html>`;
    const win = window.open('', '_blank', 'width=900,height=700');
    win.document.write(html); win.document.close(); setTimeout(() => win.print(), 500);
  };

  if (loading) return <div className="flex justify-center py-10"><Spinner size="lg" /></div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center"><h1 className="text-2xl font-bold text-gray-900 dark:text-white">Reports</h1><Button variant="secondary" onClick={handlePrint}><Printer size={16} /> Print</Button></div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="text-center"><Package size={20} className="mx-auto text-primary-500 mb-2" /><p className="text-3xl font-extrabold text-primary-600">{data?.totalProducts||0}</p><p className="text-xs text-gray-500">Products</p></Card>
        <Card className="text-center"><ShoppingCart size={20} className="mx-auto text-blue-500 mb-2" /><p className="text-3xl font-extrabold text-blue-600">{data?.todaySales||0}</p><p className="text-xs text-gray-500">Today Sales</p></Card>
        <Card className="text-center"><Wrench size={20} className="mx-auto text-purple-500 mb-2" /><p className="text-3xl font-extrabold text-purple-600">{data?.activeRepairs||0}</p><p className="text-xs text-gray-500">Active Repairs</p></Card>
        <Card className="text-center"><DollarSign size={20} className="mx-auto text-green-500 mb-2" /><p className="text-3xl font-extrabold text-green-600">{formatCurrency(data?.monthRevenue||0)}</p><p className="text-xs text-gray-500">Revenue</p></Card>
      </div>
    </div>
  );
}